### ISSUE TITLE
Implementirati prijavu

### ISSUE THREAD

**Issue by stajcicb** [psi-projekat/psi-projekat#29]
Implementirati prijavu korisnika.

Napomena: pre pocetka rada procitati poglavlje 2.6. iz [contributing.md](https://github.com/psi-projekat/psi-projekat/blob/master/contributing.md)

Uputstvo:
1. Pogledati kako je uradjena [registracija](https://github.com/psi-projekat/psi-projekat/pull/28)
2. Korisnik salje nick i lozinku
3. Server vraca ili gresku ili token
4. U folderu `src/php/queries` dodati novi fajl login.php (pogledati `blank.php` i `register.php`)
5. Dodati novi metod u `src/www/projects/main/backend/methods.js`
6. U fajlu `src/node/servers/data/methods.js` dodati novi asinhroni metod
7. Token se generise pre prijave, dakle prvo se generise token (koristiti klasu iz `token.js`) i onda se `php.exec` poziva kao `php.exec('login', {token, nick, pass})` (pogledati registraciju kako je uradjena)
8. Obavezno proveriti da li sve radi pre otvaranja PR

Potrebno je instalirati PHP, MySQL, Electron, WAMP (WAMP automatski instalira PHP i MySQL).
Prvo treba pokrenuti `init.bat` is komandne linije i to mora da prodje bez gresaka.
Takodje, treba u `config/config.json` izmeniti sve `exe` putanje da pokazuju na putanju gde je instaliran dati program.

Na adresi <http://localhost/phpmyadmin> nalazice se WAMP server (nakon instalacije) gde mozete videti podatke iz baze podataka.

### Pokretanje aplikacije

Dvoklik na `start.bat`, onda jos jednom kliknuti enter. Server se restartuje tako sto iz nove komandne linije ukucate `taskkill /f /im electron.exe`, a onda ponovo kliknete enter u prvoj komandnoj liniji.

**Comment by kristinaarna** [comment]
Pitanja vezana za neke delove koda:

   Funkcije koje ne razumem sta tacno rade:
      $sth->execute([$args->nick]);

      $num = (int)$sth->fetchColumn();

      $pdo->prepare('
          insert into User (
            nick,
            email,
            passHash,
            isMod
          ) values (?, ?, ?, false)
        ')->execute([
          $args->nick,
          $args->email,
          $args->passHash,
        ]);

Takodje nisam sigurna za token, da li mogu samo:
   const {token}= new Token(); u login.js

**Comment by stajcicb** [comment]
> Funkcije koje ne razumem sta tacno rade

`$pdo` je objekat za rad sa bazom podataka.
`$pdo->prepare(...)` priprema novi SQL upit (to i dalje nije gotov upit, jer moze sadrzati znakove pitanja (kao u primeru iznad), ti znakovi pitanja su placeholderi za vrednosti koje ce se ubaciti)
`$pdo->prepare(...)->execute([...])` zamenjuje svaki upitnik u SQL upitu odgovarajucom vrednoscu.
Ne znam tacno sta nije jasno u toj skripti

> Takodje nisam sigurna za token, da li mogu samo:
const {token}= new Token(); u login.js

U kom `login.js`? Ako mislis na `src/www/projects/main/dom/pages/login.js` tu definitivno ne, to je klijentska skripta. Treba u serverskoj skripti `method.js` da se generise token.
Takodje `const {token} = new Token()` nema smisla. Pogledati kako je generisam token u `captcha.js`

Jos neke napomene: za debugovanje moguce je koristiti funkciju `log`. Ona ispisuje bilo koju vrednost na standardnom izlazu (moze string, integer, objekat, itd). Na primer mozes pozvati `log(token)` da proveris da li je token ispravno generisan (naravno, na kraju treba obrisati `log`).

**Comment by kristinaarna** [comment]
Ok, hvala!
